##
## Aircon and Floor heater
##

- alias: Comfort Bedroom Night
  trigger:
    - platform: time
      at: '22:00:00'
    - platform: time
      at: '23:30:00'
    - platform: state
      entity_id: group.all_devices
      from: 'not_home'
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: time
        after: '22:00:00'
        before: '02:00:00'
  action:
    - service: script.turn_on
      entity_id: script.heat_bedroom_demand

- alias: Comfort Living Night
  trigger:
    - platform: numeric_state
      entity_id: proximity.home
      below: 1500
  condition:
    condition: and
    conditions:
      - condition: time
        after: '17:00:00'
        before: '02:00:00'
  action:
    - service: script.turn_on
      entity_id: script.heat_living_demand
    - service: script.turn_on
      entity_id: script.cool_living_demand

- alias: Comfort Living Morning
  trigger:
    - platform: time
      at: '07:10:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.heat_living_demand
    - service: script.turn_on
      entity_id: script.cool_living_demand

- alias: Off Living Morning
  trigger:
    - platform: time
      at: '08:59:00'
  condition:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.off_living

