##
## dish washer
##

- alias: Dish Washer Beep Off
  trigger:
    - platform: state
      entity_id: binary_sensor.dishwasher
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  action:
    - service: switch.turn_off
      entity_id: switch.washer
    - delay:
        seconds: 15
    - service: switch.turn_on
      entity_id: switch.washer

