##
## living fan automation
##

- alias: On Living Fan
  trigger:
    - platform: state
      entity_id: climate.living_aircon
      to: 'heat'
    - platform: state
      entity_id: climate.living_aircon
      to: 'cool'
    - platform: state
      entity_id: climate.living_aircon
      to: 'auto'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.ceiling_fan
    - service: homeassistant.turn_on
      entity_id: fan.living_circulator

- alias: Off Living Fan
  trigger:
    - platform: state
      entity_id: climate.living_aircon
      to: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.ceiling_fan
    - service: homeassistant.turn_off
      entity_id: fan.living_circulator

