##
## FFxiv kujitenda
##

- alias: Kujitenda start
  trigger:
    - platform: time
      at: '21:00:00'
  condition:
    - condition: time
      weekday:
        - sat
  action:
    - service: script.turn_on
      entity_id: script.notify_kujitenda0

- alias: Kujitenda end
  trigger:
    - platform: time
      at: '21:50:00'
  condition:
    - condition: time
      weekday:
        - sat
  action:
    - service: script.turn_on
      entity_id: script.notify_kujitenda1

