##
## FFxiv kujitenda
##

- alias: Kujitenda start
  trigger:
    - platform: time
      at: '21:00:00'
  condition:
    - condition: time
      weekday:
        - sat
  action:
    - service: tts.google_say
      entity_id: media_player.google_living
      data_template:
        message: >
          {{ [
          "ジャンボくじテンダーの時間ですよ。",
          "ジャンボくじテンダーの時間になりました。"
          ] | random }}

- alias: Kujitenda end
  trigger:
    - platform: time
      at: '21:50:00'
  condition:
    - condition: time
      weekday:
        - sat
  action:
    - service: tts.google_say
      entity_id: media_player.google_living
      data_template:
        message: >
          {{ [
          "ジャンボくじテンダーの交換しましたか？",
          "ジャンボくじテンダーの時間、終わっちゃうよ？"
          ] | random }}
 
