##
## home
##

- alias: Return Home
  trigger:
    - platform: numeric_state
      entity_id: proximity.home2
      below: 5000
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.my_devices
        state: 'home'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
      - condition: time
        after: '16:00:00'
        before: '02:00:00'
  action:
    - service: notify.ios_iphonex
      data:
        message: "お知らせ"
        data:
          push:
            sound: "se_chakushin.wav"

- alias: Unknown Person
  trigger:
    - platform: state
      entity_id: sensor.hue_motion_motion_sensor
      to: 'on'
      for:
        seconds: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family_devices
        state: 'not_home'
  action:
    - service: notify.ios_iphonex
      data:
        message: "誰か家にいます"
        data:
          push:
            sound: "se_mysterious3.wav"

