##
## season
##

- alias: Season Spring
  trigger:
    - platform: state
      entity_id: sensor.season
      to: 'spring'
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: sensor.season
      state: 'spring'
  action:
    - service: group.set_visibility
      entity_id: group.useful_spring
      data:
        visible: true
    - service: group.set_visibility
      entity_id: group.useful_summer
      data:
        visible: false
    - service: group.set_visibility
      entity_id: group.useful_autumn
      data:
        visible: false
    - service: group.set_visibility
      entity_id: group.useful_winter
      data:
        visible: false

- alias: Season Summer
  trigger:
    - platform: state
      entity_id: sensor.season
      to: 'summer'
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: sensor.season
      state: 'summer'
  action:
    - service: group.set_visibility
      entity_id: group.useful_spring
      data:
        visible: false
    - service: group.set_visibility
      entity_id: group.useful_summer
      data:
        visible: true
    - service: group.set_visibility
      entity_id: group.useful_autumn
      data:
        visible: false
    - service: group.set_visibility
      entity_id: group.useful_winter
      data:
        visible: false

- alias: Season Autumn
  trigger:
    - platform: state
      entity_id: sensor.season
      to: 'autumn'
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: sensor.season
      state: 'autumn'
  action:
    - service: group.set_visibility
      entity_id: group.useful_spring
      data:
        visible: false
    - service: group.set_visibility
      entity_id: group.useful_summer
      data:
        visible: false
    - service: group.set_visibility
      entity_id: group.useful_autumn
      data:
        visible: true
    - service: group.set_visibility
      entity_id: group.useful_winter
      data:
        visible: false

- alias: Season Winter
  trigger:
    - platform: state
      entity_id: sensor.season
      to: 'winter'
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: sensor.season
      state: 'winter'
  action:
    - service: group.set_visibility
      entity_id: group.useful_spring
      data:
        visible: false
    - service: group.set_visibility
      entity_id: group.useful_summer
      data:
        visible: false
    - service: group.set_visibility
      entity_id: group.useful_autumn
      data:
        visible: false
    - service: group.set_visibility
      entity_id: group.useful_winter
      data:
        visible: true

