##
## tomorrow weather and informations
##

- alias: Tomorrow Info
  trigger:
    - platform: time
      at: '00:00:00'
    - platform: time
      at: '01:00:00'
  action:
    - service: tts.google_say
      entity_id: media_player.google_living
      data_template:
        message: >
          {{ states('sensor.weather_forecast') }}
          {{ states('sensor.weather_forecast') }}
          {% if not is_state('sensor.trash_day', 'off') %}
            "あと、"
            {{ states('sensor.trash_day') }}
            {{ states('sensor.trash_day') }}
          {% endif %}
          {% if not is_state('sensor.visit_schedule', '') %}
            "明日は仕事の外出予定があります。"
          {% endif %}

