# binary_sensor

- platform: workday
  country: JP

- platform: template
  sensors:
    dishwasher:
      delay_off:
        minutes: 10
      value_template: >-
        {{ states.switch.washer.attributes.current_power_w|float > 5 }}

