# binary_sensor

- platform: workday
  country: JP

- platform: template
  sensors:
    dishwasher:
      delay_off:
        minutes: 10
      value_template: >-
        {{ states.switch.washer.attributes.current_power_w|float > 5 }}

- platform: bayesian
  name: 'Need Heat'
  prior: 0.2
  probability_threshold: 0.90
  observations:
    - entity_id: sensor.season
      prob_given_true: 0.70
      platform: state
      to_state: 'winter'
    - entity_id: sensor.outdoor
      prob_given_true: 0.90
      platform: numeric_state
      below: 16
    - entity_id: sensor.living_temperature
      prob_given_true: 0.80
      platform: numeric_state
      below: 25
    - entity_id: sensor.bedroom_temperature
      prob_given_true: 0.80
      platform: numeric_state
      below: 20

- platform: bayesian
  name: 'Need Cool'
  prior: 0.2
  probability_threshold: 0.90
  observations:
    - entity_id: sensor.season
      prob_given_true: 0.70
      platform: state
      to_state: 'summer'
    - entity_id: sensor.outdoor
      prob_given_true: 0.90
      platform: numeric_state
      above: 27
    - entity_id: sensor.living_temperature
      prob_given_true: 0.80
      platform: numeric_state
      above: 27
    - entity_id: sensor.bedroom_temperature
      prob_given_true: 0.80
      platform: numeric_state
      above: 27

