# binary_sensor

- platform: workday
  country: JP

- platform: template
  sensors:
    dishwasher:
      delay_off:
        minutes: 10
      value_template: >-
        {{ states.sensor.dishwasher_power.state|float > 3 }}

- platform: threshold
  name: cond_hot
  entity_id: sensor.outdoor_stat_mean
  upper: 24
  hysteresis: 1.0

- platform: threshold
  name: cond_cold
  entity_id: sensor.outdoor_stat_mean
  lower: 16
  hysteresis: 1.0

- platform: threshold
  name: cond_very_cold
  entity_id: sensor.outdoor_stat_mean
  lower: 13
  hysteresis: 1.0

