# binary_sensor

- platform: workday
  country: JP
  add_holidays:
    - '2019-08-13'
    - '2019-08-14'
    - '2019-08-15'
    - '2019-08-16'
    - '2019-12-30'
    - '2019-12-31'
    - '2020-01-02'
    - '2020-08-10'
    - '2020-08-11'
    - '2020-08-12'
    - '2020-08-13'
    - '2020-08-14'

- platform: template
  sensors:
    dishwasher:
      delay_off:
        minutes: 10
      value_template: >-
        {{ states.sensor.dishwasher_power.state|float > 2.3 }}

- platform: threshold
  name: cond_hot
  entity_id: sensor.outdoor_average
  upper: 24.5
  hysteresis: 0.5

- platform: threshold
  name: cond_cold
  entity_id: sensor.outdoor_average
  lower: 15.5
  hysteresis: 0.5

- platform: threshold
  name: cond_very_cold
  entity_id: sensor.outdoor_average
  lower: 12.0
  hysteresis: 0.5

