# binary_sensor

- platform: workday
  country: JP
  add_holidays:
    - '2019-08-13'
    - '2019-08-14'
    - '2019-08-15'
    - '2019-08-16'

- platform: template
  sensors:
    dishwasher:
      delay_off:
        minutes: 10
      value_template: >-
        {{ states.sensor.dishwasher_power.state|float > 2.3 }}

- platform: threshold
  name: cond_hot
  entity_id: sensor.outdoor_stat_mean
  upper: 24
  hysteresis: 0.9

- platform: threshold
  name: cond_cold
  entity_id: sensor.outdoor_stat_mean
  lower: 15.5
  hysteresis: 0.9

- platform: threshold
  name: cond_very_cold
  entity_id: sensor.outdoor_stat_mean
  lower: 11.5
  hysteresis: 0.9

