# circulator (fan)

- platform: mqtt
  name: "Living Circulator"
  state_topic:         "circulator/living/power"
  command_topic:       "circulator/living/power/set"
  speed_state_topic:   "circulator/living/speed"
  speed_command_topic: "circulator/living/speed/set"
  payload_on:  "ON"
  payload_off: "OFF"
  payload_low_speed:    "low"
  payload_medium_speed: "medium"
  payload_high_speed:   "high"
  speeds:
    - "low"
    - "medium"
    - "high"

