# circulator (fan)

- platform: mqtt
  name: "Living Circulator"
  state_topic:         "circulator/livingroom/power"
  command_topic:       "circulator/livingroom/power/set"
  speed_state_topic:   "circulator/livingroom/fanmode"
  speed_command_topic: "circulator/livingroom/fanmode/set"
  payload_on:  "on"
  payload_off: "off"
  payload_low_speed:    "low"
  payload_medium_speed: "medium"
  payload_high_speed:   "high"
  speeds:
    - "off"
    - low
    - medium
    - high

