# climate

- platform: mqtt
  name: "Living Aircon"
  modes:
    - "auto"
    - "cool"
    - "heat"
    - "off"
  swing_modes:
    - auto
  fan_modes:
    - auto
  current_temperature_topic: "sensor/living/temperature"
  power_command_topic:       "aircon/living/power/set"
  power_state_topic:         "aircon/living/power"
  mode_command_topic:        "aircon/living/mode/set"
  mode_state_topic:          "aircon/living/mode"
  temperature_command_topic: "aircon/living/temperature/set"
  temperature_state_topic:   "aircon/living/temperature"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "Bedroom Aircon"
  modes:
    - "auto"
    - "cool"
    - "heat"
    - "off"
  swing_modes:
    - auto
  fan_modes:
    - auto
  current_temperature_topic: "sensor/bedroom/temperature"
  power_command_topic:       "aircon/bedroom/power/set"
  power_state_topic:         "aircon/bedroom/power"
  mode_command_topic:        "aircon/bedroom/mode/set"
  mode_state_topic:          "aircon/bedroom/mode"
  temperature_command_topic: "aircon/bedroom/temperature/set"
  temperature_state_topic:   "aircon/bedroom/temperature"
  payload_on: "ON"
  payload_off: "OFF"

