homeassistant:
  name: Home
  latitude:  !secret home_latitude
  longitude: !secret home_longitude
  elevation: 18
  unit_system: metric
  time_zone: Asia/Tokyo

  whitelist_external_dirs:
    - '/config/doorphone'

  customize: !include customize.yaml
  customize_glob:
    "script.*":
      hidden: true
    "automation.*":
      hidden: true

recorder:
  purge_interval: 2
  purge_keep_days: 6
  include:
    entities:
      - binary_sensor.dishwasher
      - binary_sensor.workday_sensor
    domains:
      - sensor
      - switch
      - climate
      - media_player
      - device_tracker
      - lock
  exclude:
    entities:
      - switch.blind
      - switch.ceiling_fan
      - sensor.season
      - sensor.trash_day
      - sensor.visit_schedule
      - sensor.weather_forecast

zone:
  name: Home
  latitude:  !secret home_latitude
  longitude: !secret home_longitude
  radius: 450
  icon: mdi:home

proximity:
  home:
    devices:
      - device_tracker.iphonex
    tolerance: 100
    unit_of_measurement: m
  home2:
    devices:
      - device_tracker.iphone_se
    tolerance: 100
    unit_of_measurement: m

http:
  api_password: !secret http_password
  base_url:     !secret http_base_url

mqtt:
  broker: !secret mqtt_broker

netatmo:
  api_key:    !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username:   !secret netatmo_username
  password:   !secret netatmo_password

wemo:
  static:
    - 192.168.0.37

ios:

homekit:
  pincode: !secret homekit_pincode

device_tracker:
#  - platform: bluetooth_tracker
#  - platform: icloud
#    username: !secret icloud_username
#    password: !secret icloud_password
#    consider_home: 900

google_assistant:
  project_id:   !secret google_project_id
  client_id:    !secret google_client_id
  access_token: !secret google_access_token
  api_key:      !secret google_api_key
  exposed_domains:
    - climate
    - media_player
    - script
#    - scene

frontend:
config:
discovery:
history:
logbook:
#map:
sun:

switch: !include switch.yaml
climate: !include climate.yaml
sensor: !include sensor.yaml

binary_sensor:
  - platform: workday
    country: JP
  - platform: template
    sensors:
      dishwasher:
        delay_off:
          minutes: 10
        value_template: >-
          {{ states.switch.washer.attributes.current_power_w|float > 5 }}

lock:
  - platform: mqtt
    name: "Door Lock"
    command_topic:  "dio/set3"
    state_topic:    "dio/in3"
    payload_lock:   "1"
    payload_unlock: "0"
    retain: true
 
camera:
  - platform: local_file
    name: Doorphone
    file_path: /config/doorphone/latest.jpg

tts:
  - platform: google
    language: 'ja'
    time_memory: 100

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include_dir_merge_named script/

