homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude:  !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 18
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Tokyo
  # can access dirs
  whitelist_external_dirs:
    - '/config/doorphone'
  # Customization file
  customize: !include customize.yaml
  # Customization globbing
  customize_glob:
    "script.*":
      hidden: true
    "automation.*":
      hidden: true

recorder:
  purge_interval: 2
  purge_keep_days: 6
  include:
    entities:
      - binary_sensor.dishwasher
      - binary_sensor.workday_sensor
    domains:
      - sensor
      - switch
      - climate
      - media_player
      - device_tracker
      - lock

zone:
  name: Home
  latitude:  !secret home_latitude
  longitude: !secret home_longitude
  radius: 450
  icon: mdi:home

proximity:
  home:
    devices:
      - device_tracker.iphonex
    tolerance: 100
    unit_of_measurement: m

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  base_url:     !secret http_base_url

mqtt:
  broker: !secret mqtt_broker

netatmo:
  api_key:    !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username:   !secret netatmo_username
  password:   !secret netatmo_password

wemo:
  static:
    - 192.168.0.37

homekit:
  pincode: !secret homekit_pincode

ios:

device_tracker:
#  - platform: bluetooth_tracker
#  - platform: icloud
#    username: !secret icloud_username
#    password: !secret icloud_password
#    consider_home: 900

google_assistant:
  project_id:   !secret google_project_id
  client_id:    !secret google_client_id
  access_token: !secret google_access_token
  api_key:      !secret google_api_key
  exposed_domains:
    - climate
    - fan
    - media_player
    - script
#    - scene

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
#map:

# Track the sun
#sun:

switch: !include switch.yaml
climate: !include climate.yaml
sensor: !include sensor.yaml

binary_sensor:
  - platform: workday
    country: JP
  - platform: template
    sensors:
      dishwasher:
        delay_off:
          minutes: 10
        value_template: >-
          {{ states.switch.washer.attributes.current_power_w|float > 5 }}

fan:
  - platform: mqtt
    name: "Living Ceiling Fan"
    command_topic: "fan/living/power"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: true
    speeds:
      - soft

lock:
  - platform: mqtt
    name: "Door Lock"
    command_topic:  "dio/set3"
    state_topic:    "dio/in3"
    payload_lock:   "1"
    payload_unlock: "0"
    retain: true
 
camera:
  - platform: local_file
    name: Doorphone
    file_path: /config/doorphone/latest.jpg

tts:
  - platform: google
    language: 'ja'
    time_memory: 100

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include_dir_merge_named script/

