homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude:  !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 18
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Tokyo
  # can access dirs
  whitelist_external_dirs:
    - '/config/doorphone'
  # Customization file
  customize: !include customize.yaml
  # Customization globbing
  customize_glob:
    "script.notify_*":
      hidden: true
    "script.off_*":
      hidden: true
    "script.check_*":
      hidden: true
    "automation.*":
      hidden: true

recorder:
  purge_interval: 2
  purge_keep_days: 6
  include:
    entities:
      - binary_sensor.dishwasher
      - binary_sensor.workday_sensor
    domains:
      - sensor
      - switch
      - climate
      - media_player
      - device_tracker
      - lock

zone:
  name: Home
  latitude:  !secret home_latitude
  longitude: !secret home_longitude
  radius: 450
  icon: mdi:home

proximity:
  home:
    devices:
      - device_tracker.iphonex
    tolerance: 100
    unit_of_measurement: m

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  base_url:     !secret http_base_url

mqtt:
  broker: !secret mqtt_broker

netatmo:
  api_key:    !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username:   !secret netatmo_username
  password:   !secret netatmo_password

wemo:
  static:
    - 192.168.0.37

homekit:
  pincode: !secret homekit_pincode

ios:

device_tracker:
  - platform: bluetooth_tracker
#  - platform: icloud
#    username: !secret icloud_username
#    password: !secret icloud_password
#    consider_home: 900

google_assistant:
  project_id:   !secret google_project_id
  client_id:    !secret google_client_id
  access_token: !secret google_access_token
  api_key:      !secret google_api_key
  exposed_domains:
    - climate
    - fan
    - media_player
    - script
#    - scene

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
#map:

# Track the sun
#sun:

climate: !include climate.yaml
sensor: !include sensor.yaml

binary_sensor:
  - platform: workday
    country: JP
  - platform: template
    sensors:
      dishwasher:
        delay_off:
          minutes: 10
        value_template: >-
          {{ states.switch.washer.attributes.current_power_w|float > 5 }}

fan:
  - platform: mqtt
    name: "Living Ceiling Fan"
    command_topic: "fan/living/power"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: true
    speeds:
      - soft

switch:
  - platform: mqtt
    name: "Floor Heater Living"
    command_topic: "dio/set0"
    state_topic:   "dio/in0"
    payload_on:  "1"
    payload_off: "0"
    retain: true
  - platform: mqtt
    name: "Floor Heater Kitchen"
    command_topic: "dio/set1"
    state_topic:   "dio/in1"
    payload_on:  "1"
    payload_off: "0"
    retain: true

  - platform: template
    switches:
      heat_living:
        value_template: >-
          {{     is_state('climate.living_aircon', 'heat')
             and is_state('switch.floor_heater_living', 'on')
             and is_state('switch.floor_heater_kitchen', 'on') }}
        turn_on:
          service: script.turn_on
          entity_id: script.heat_living
        turn_off:
          service: script.turn_on
          entity_id: script.off_living
      heat_bedroom:
        value_template: >-
          {{ is_state('climate.bedroom_aircon', 'heat') }}
        turn_on:
          service: script.turn_on
          entity_id: script.heat_bedroom
        turn_off:
          service: script.turn_on
          entity_id: script.off_bedroom

  - platform: broadlink
    host: 192.168.0.39
    mac: '78:0f:77:00:01:33'
    timeout: 20
    switches:
      ceiling_fan:
        command_on: 'JgCEAxANEAwRKRAMESkQKRAMEQwQKREMEA0QDBEMECkQDRAMEQwQDRApECkQDRAMESkQDBEMEA0QDBApEQwQDRApEA0QDBANEAwRDBANEAwRDBAMESkQDBEMEA0QKRANEAAKGXM3EQwQKREMEA0QDBEMEA0QDBANEAwRDBANEAwRKRAMEA0QDBEMEA0QDBEpEAwQKREpEAwRDBApEA0QDBEMEA0QKRANEAwQDRAMESkQKRANEAwQKREMEA0QDBEMECkQDRAMESkQDBEMEA0QDBANEAwRDBANEAwRKRAMEA0QDBEpEAwRAAoYdDcRDBApEA0QDBEMEA0QDBEMEA0QDBANEAwRDBApEQwQDRAMEA0QDBEMECkRDBApECkRDBANECkQDRAMEA0QDBEpEAwRDBANEAwQKREpEAwRDBApEA0QDBEMEA0QKRANEAwQKREMEA0QDBEMEA0QDBANEA0QDBApEQwQDRAMECoQDBAAChl0NxANECkQDRAMEQwQDBEMEA0QDBEMEA0QDBANECkQDRAMEQwQDRAMEA0QKRANECkQKRANEAwRKRAMEQwQDRAMECoQDBANEAwRDBApESkQDBANECkQDRAMEQwQDRApEAwRDBApEQwQDRAMEA0QDBEMEA0QDBEMECkQDRAMEQwQKREMEAAKGXQ3EA0QKRAMEQwQDRAMEQwQDRAMEQwQDBEMEA0QKRANEAwQDRAMEQwQDRApEA0QKRApEA0QDBEpEAwRDBANEAwQKREMEA0QDBEMECkQKREMEA0QKRAMEQwQDRAMESkQDBEMECkQDRAMEQwQDRAMEQwQDRAMEA0QKRANEAwRDBApEA0QAAoZczgQDBAqEAwQDRAMEQwQDRAMEA0QDRAMEA0QDBEpEAwQDRANEAwQDRAMESkQDBAqECkQDBEMECkQDRANEAwQDRApEA0QDBANEA0QKRApEA0QDBAqEAwQDRAMEQwQKRANEA0QKRAMEQwQDRAMEQwQDRAMEA0QDBEpEAwQDRANECkQDBEAChlzOBAMECkRDBANEAwRDBANEAwQDRAMEQwQDRAMESkQDBANEAwRDBANEAwRKRAMECkRKRAMEQwQKRANEAwRDBANECkQDRAMEA0QDBEpECkQDRAMECkRDBANEAwRDBApEA0QDRApEAwRDBANEAwRDBANEAwQDRAMESkQDBEMEAwRKRAMEQANBQAAAAA='
        command_off: 'JgCEAxAMEQwQKRANECkQKREMEA0QKRAMEQwQDRAMESkQDBANEAwRDBApESkQDBANECkQKREMEA0QKRApEA0QDBEMEA0QDBANECkQKREMEAwRKRApECkRDBAMESkQKRANEAAKGXQ3EQwQKREMEA0QDBEMEAwRDBANEAwRDBANEAwQKREMEA0QDBEMEA0QDBApEQwQKREpEAwQDRApEA0QDBEMEA0QKRAMEQwQDRAMESkQKRAMEQwQKREpEAwQDRApECkRDBANEAwQDRAMEQwQKREpEAwQDRApECkRKBEMEA0QKRApEQwQAAoaczgQDBEpEAwQDRAMEQwQDRAMEQwQDRAMEA0QDBEpEAwRDBANEAwQDRAMESkQDBEpECkQDBEMECkRDBANEAwQDRApEA0QDBEMEA0QKRApEA0QDBEpECkQDBEMECkRKBEMEA0QDBEMEA0QDBApESkQDBEMECkQKREpEAwRDBApECkRDBAAChpzOBANECkQDBEMEA0QDBEMEA0QDQ8NEAwRDBANECkQDRAMEA0QDBEMEA0QKRANECkQKRANEAwRKRAMEA0QDBEMECkRDBANEAwQDRApECkRDBANECkQKRANEAwRKRApEAwRDBANEAwRDBANECkQKRANEAwQKhApECkQDRAMECkRKRAMEQAKGXQ3EA0QKRANEAwRDBANEAwQDRAMEQwQDRAMEQwQKRANEAwRDBANEAwRDBApEA0QKRApEQwQDRApEAwRDBANEAwRKRAMEA0QDBEMECkRKRAMEA0QKRApEQwQDBEpECkQDRAMEQwQDRAMEA0QKRApEQwQDRApECkQKREMEA0QKRApEA0QAAoZdDcRDBApEQwQDRAMEA0QDBEMEA0QDBEMEA0QDBApEQwQDRAMEQwQDRAMECkRDBApESgRDBANECkQDRAMEQwQDRApEAwRDBANEAwRKBEpEAwRDBApESgRDBANECkQKREMEA0QDBANEAwRDBApESgRDBANECkQKREoEQwQDRApECkRDBAAChpzOBAMESgRDBANEAwRDBANEAwRDBANEAwQDRAMESkQDBANEAwRDBANEAwRKRAMECkRKRAMEA0QKRANEAwRDBANECkQDRAMEA0PDRAqECkQDQ8NDyoQKg8NDw4PKg8qDw4ODw4ODg8ODw4ODisPKw8NDg8OKw4rDiwPDQ4PDisOKRAPDgANBQAAAAA='

      blind:
        # close blind
        command_on: 'JgByAwABF4kTDxMQEzITMhQyEw8UDxMQE4gUMhMQEw8TEBMPFA8TEBMPFAADGQABF4gTEBMPFDITMhMyFA8TEBMPE4kTMhQPExATDxQPExATDxQPEwADGgABFIsSEBMQEzIUMhMyFA4UDxQPFIgTMhQPEw8UDxQOExAUDxMPEwADGgABF4gTEBMQEjMRNBE0ERIREhEREYsRNBESERIRERESERIRERESEQADHAABFokTDxQPEzIUMhMyExATDxMQE4kTMhMQEw8UDxMQEw8UDxMQEwADGQABF4gUDxMQEzITMhMzEw8TEBMPFIgUMhMPExATEBMPExATDxQPEwADGgABFokTEBMPEzIUMhMyExATDxQPE4kTMhMQEw8UDxMQEw8UDxMQEwADGQABF4gUDxMQEzITMhMzEw8TEBMPFIgUMhMPFA8TEBMPExATEBMPEwADGgABFokUDxMPEzIUMhMyExATDxQPE4kUMRQPEw8UDxMQEw8UDxMQEwADGQABGIcUDxMQEzIUMRQyFA4TEBMQE4gUMhQOFA8TEBMPExATEBMPEwADGgABF4gUDxMPEzMUMRQxFA8TDxQPE4kUMRQPExATDxMQEw8UDxMQEwADGQABGIcUDxMQEzITMhQyFA4TEBMQE4gUMhQOFA8TEBMPFA8TEBMPEwADGgABF4gUDxMPEzMUMRQxFA8TEBMPE4kUMRQPFA8UDhMQExATDxMQEwADGQABGIgUDhMQEzIUMRQyFA4UDxMQE4kUMRQPEw8TEBMPFA8TEBMPFAADGQABF4gUDxMPFDIUMRQxFA8TEBMPE4kUMRQPExATDxMQExATDxMQEwADGQABGIgUDhQPEzIUMhMyFA4UDxMQE4kUMRQPEw8UDxMQEw8TEBMPFAADGQABGIcUDxQOFDIUMRQxFA8TEBMPE4kUMRQPExATDxQPExATDxMQEwADGgABF4gUDhQPEzIUMhQxFA8TDxMQE4kUMRQPEw8TEBMQEw8TEBMQEwADGQABGIcUDxMQEzIUMRQxFA8TEBMPE4kUMhMPFA8TDxQPExATDxQPEwADGgABF4gUDhQPEzIUMhQxFA8TDxMQE4kUMRQPEw8TEBMQEw8TEBMQEwADGQABF4gTEBMQEzITMhMyExATEBMPE4kTMxMPExATDxMQExATDxMQEwANBQAAAAAAAA=='
        # close open
        command_off: 'JgAeAwABF4gTEBMQEzITMhMzEw8TEBMQE4YVEBMyExATMhMQExATDxMQEwAC9wABFokTEBMPEzMTMhMyExATEBIQE4kTEBMyExATMhMQEw8TEBMQEgAC9wABF4kTDxMQEzITMxMyExASEBMQE4kTDxMzEw8TMxMPExATEBIQEwAC9wABF4gTEBMQEzITMhMzEhATEBMPE4kTEBMyExATMhMQExASEBMQEwAC9wABFokTEBMPEzMSMxMyExATDxMQE4kTEBMyExASMxMQEhATEBMPEwAC9wABF4gUDxMQEzITMxIzEw8TEBMQE4kTDxMzEhATMhMQExATDxMQEwAC9wABF4gTEBMQEjMTMhMyExATEBMPE4kTEBMyExATMhMQEw8TEBMQEwAC9wABFokTEBIQEzITMxMyExATDxMQE4kTEBIzEw8TMxMPExATEBMPEwAC9wABF4gTEBMQEzITMhMzEw8TEBMQEokTEBMyExATMhMQExATDxMQEwAC9wABFokTEBMPEzMTMhMyExATEBIQE4kTEBMyExATMhMQEw8TEBMQEgAC9wABF4kTDxMQEzITMxIzExASEBMQE4kTDxMzEw8TMxIQExATEBIQEwAC9wABF4gTEBMQEjMTMhMyExATEBMPE4kTEBMyExATMhMQExASEBMQEwAC9wABFokTEBIQEzITMxMyExATDxMQE4kTEBIzExASMxMPExATEBMPEwAC9wABF4gUDxMQEzITMhMzEw8TEBMQE4gTEBMyExATMhMQExATDxMQEwAC9wABFokTEBMPEzMTMhMyExATEBIQE4kTEBMyExATMhMQEw8TEBMQEgAC+AABFokTDxMQEzITMxIzExASEBMQE4kTDxMzEw8TMxMPExATEBIQEwAC9wABF4gTEBMQEzITMhMzEhATEBMQEokTEBMyExATMhMQExASEBMQEwAC9wABFokTEBMPEzMSMxMyExATDxMQE4kTEBMyExASMxMQEhATEBMPEwAC9QABGYkTDxMQEzITMhMzEw8TEBMQE4kTDxMyExATMhMQExATDxMQEwANBQAAAAAAAAAAAAA='

lock:
  - platform: mqtt
    name: "Door Lock"
    command_topic:  "dio/set3"
    state_topic:    "dio/in3"
    payload_lock:   "1"
    payload_unlock: "0"
    retain: true
 
camera:
  - platform: local_file
    name: Doorphone
    file_path: /config/doorphone/latest.jpg

# Text to speech
tts:
  - platform: google
    language: 'ja'
    time_memory: 100

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include_dir_merge_named script/

