homeassistant:
  name: Home
  latitude:  !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  external_url: !secret external_url
  internal_url: !secret internal_url
  unit_system: metric
  time_zone: Asia/Tokyo

  allowlist_external_dirs:
    - '/config/doorphone'
    - '/config/text'

  customize: !include customize.yaml
  customize_glob:
    "script.*":
      hidden: true
    "automation.*":
      hidden: true
    "device_tracker.*":
      hidden: true
    "person.*":
      hidden: true

recorder:
  purge_keep_days: 10
  include:
    entities:
      - climate.bedroom_aircon
      - climate.living_aircon
      - device_tracker.iphonex_gps
      - device_tracker.iphone11_gps
      - input_boolean.sleeping
      - sensor.jr_info
      - sensor.living_temperature
      - sensor.living_humidity
      - sensor.bedroom_temperature
      - sensor.bedroom_humidity
      - sensor.outdoor_temperature
      - sensor.outdoor_average
      - sensor.netatmo_house_co2
      - sensor.netatmo_house_humidity
      - sensor.netatmo_house_noise
      - sensor.netatmo_house_pressure
      - sensor.netatmo_house_temperature
      - sensor.netatmo_outdoor_humidity
      - sensor.netatmo_outdoor_temperature
      - sensor.dishwasher_power
      - sensor.house_power
      - sensor.entrance_lux
      - sensor.entrance_temp
      - switch.floor_heater_kitchen
      - switch.floor_heater_living
    domains:
      - binary_sensor
      - media_player
      - lock
      - fan
      - proximity
  exclude:
    domains:
      - automation
      - camera
      - climate
      - device_tracker
      - group
      - light
      - remote
      - script
      - sensor
      - switch
      - person

zone:
  name: Home
  latitude:  !secret home_latitude
  longitude: !secret home_longitude
  radius: 300
  icon: mdi:home

proximity:
  home:
    devices:
      - person.me
    tolerance: 100
    unit_of_measurement: m
  home2:
    devices:
      - person.partner
    tolerance: 100
    unit_of_measurement: m

http:
  ip_ban_enabled: false
#  external_url: !secret http_base_url
#  internal_url: !secret http_base_url
#  api_password: !secret http_password

mqtt:
  broker: !secret mqtt_broker

netatmo:
  client_id:     !secret netatmo_id
  client_secret: !secret netatmo_secret
#  username:   !secret netatmo_username
#  password:   !secret netatmo_password

wemo:
  static:
    - 192.168.0.56

hue:

ios:
  actions:
    - name: ActionHeat
      background_color: "#884444"
      label:
        text: "暖かくする"
        color: "#ffaaaa"
      icon:
        icon: radiator
        color: "#ffffff"
    - name: ActionCool
      background_color: "#444488"
      label:
        text: "涼しくする"
        color: "#aaaaff"
      icon:
        icon: weather-windy
        color: "#ffffff"

homekit:
  filter:
    include_domains:
      - climate
      - switch
    include_entities:
      - sensor.living_temperature
      - sensor.living_humidity
      - sensor.bedroom_temperature
      - sensor.bedroom_humidity
      - sensor.outdoor_temperature
      - sensor.netatmo_house_temperature
      - sensor.netatmo_house_humidity
      - sensor.netatmo_house_co2
      - sensor.netatmo_house_noise
      - sensor.netatmo_outdoor_temperature
      - sensor.netatmo_outdoor_humidity
    exclude_domains:
      - script
      - group
    exclude_entities:
      - switch.washer
      - switch.blind

device_tracker:
  - platform: snmp
    host: 192.168.0.1
    community: !secret snmp_community
    baseoid: 1.3.6.1.2.1.4.22.1.2

#  - platform: icloud
#    username: !secret icloud_username
#    password: !secret icloud_password

google_assistant:
  project_id:   !secret google_project_id
  exposed_domains:
    - climate
    - media_player
    - script
#    - scene

#googlehome:
#  devices:
#    - host: 192.168.0.60

alexa:

frontend:
config:
discovery:
history:
logbook:
system_health:
sun:
mobile_app:
zeroconf:

person: !include person.yaml
switch: !include switch.yaml
climate: !include climate.yaml
fan: !include circulator.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml

input_boolean:
  sleeping:
    name: Sleeping
    initial: off
    icon: mdi:sleep

lock:
  - platform: mqtt
    name: "Door Lock"
    command_topic:  "dio/set3"
    state_topic:    "dio/in3"
    payload_lock:   "1"
    payload_unlock: "0"
    state_locked:   "1"
    state_unlocked: "0"
    retain: true
 
camera:
  - platform: local_file
    name: Doorphone
    file_path: /config/doorphone/latest.jpg

tts:
  - platform: google_translate
    language: 'ja'
    service_name: google_say
#tts:
#  - platform: watson_tts
#    watson_apikey: !secret watson_apikey

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include_dir_merge_named script/

