sensor.netatmo_house_wifi:
  hidden: true
sensor.outdoor_temperature:
  device_class: temperature
  friendly_name: 屋外気温 (北)
  icon: mdi:thermometer
  unit_of_measurement: °C
sensor.netatmo_house_temperature:
  friendly_name: コーナー 気温
sensor.netatmo_house_pressure:
  device_class: pressure
  friendly_name: 気圧
sensor.netatmo_house_noise:
  friendly_name: 騒音
sensor.netatmo_house_co2:
  friendly_name: CO2
sensor.netatmo_house_humidity:
  friendly_name: コーナー 湿度
  icon: mdi:water
climate.living_aircon:
  friendly_name: リビング エアコン
  icon: mdi:air-conditioner
  max_temp: 30
  min_temp: 20
climate.bedroom_aircon:
  friendly_name: 寝室 エアコン
  icon: mdi:air-conditioner
  max_temp: 30
  min_temp: 20
sensor.weather_symbol:
  friendly_name: 天気
fan.living_ceiling_fan:
  friendly_name: リビング シーリングファン
sensor.bedroom_humidity:
  device_class: humidity
  friendly_name: 寝室 湿度
  icon: mdi:water
sensor.living_humidity:
  device_class: humidity
  friendly_name: リビング 湿度
  icon: mdi:water
sensor.living_temperature:
  device_class: temperature
  friendly_name: リビング 気温
  icon: mdi:thermometer
sensor.bedroom_temperature:
  device_class: temperature
  friendly_name: 寝室 気温
  icon: mdi:thermometer
device_tracker.iphonex:
  hidden: true
proximity.home:
  hidden: true
device_tracker.iphone_se:
  hidden: true
sensor.netatmo_outdoor_radio:
  hidden: true
sensor.netatmo_outdoor_battery:
  hidden: true
sensor.netatmo_outdoor_humidity:
  friendly_name: 屋外湿度
  icon: mdi:water
sensor.netatmo_outdoor_temperature:
  friendly_name: 屋外気温 (南)
sensor.house_power:
  friendly_name: 電力
  icon: mdi:lightbulb-on
sensor.iphone_se_battery_level:
  hidden: true
sensor.iphone_se_battery_state:
  hidden: true
sensor.iphonex_battery_level:
  hidden: true
sensor.iphonex_battery_state:
  hidden: true
sensor.netatmo_house_humidity_2:
  hidden: true
sensor.netatmo_house_noise_2:
  hidden: true
sensor.netatmo_house_pressure_2:
  hidden: true
sensor.netatmo_house_temperature_2:
  hidden: true
  homebridge_hidden: true
sensor.netatmo_outdoor_humidity_2:
  hidden: true
sensor.netatmo_house_co2_2:
  hidden: true
sensor.netatmo_outdoor_temperature_2:
  hidden: true
  homebridge_hidden: true
binary_sensor.dishwasher:
  friendly_name: 食洗機
media_player.google_living:
  hidden: true
binary_sensor.workday_sensor:
  friendly_name: 平日
  hidden: true
sensor.weather_forecast:
  friendly_name: 天気予報
  hidden: true
switch.floor_heater_living:
  friendly_name: リビング 床暖
  icon: mdi:fire
switch.floor_heater_kitchen:
  friendly_name: キッチン 床暖
  icon: mdi:fire
group.living:
  friendly_name: リビング
  icon: mdi:silverware
group.music:
  friendly_name: 音楽
group.bedroom:
  friendly_name: 寝室
group.house:
  friendly_name: 家
switch.heat_living:
  friendly_name: リビングあたため
  icon: mdi:radiator
switch.heat_bedroom:
  friendly_name: 寝室あたため
  icon: mdi:radiator
sensor.doorphone_counter:
  hidden: true
device_tracker.iphonex_2:
  friendly_name: iPhoneX_bt
  hidden: true
switch.washer:
  hidden: true
sensor.doorphone:
  hidden: true
sensor.trash_day:
  hidden: true
switch.ceiling_fan:
  friendly_name: シーリングファン
  icon: mdi:fan
switch.blind:
  icon: mdi:blinds
sensor.visit_schedule:
  hidden: true
sun.sun:
  hidden: true
sensor.season:
  hidden: true
switch.cool_living:
  friendly_name: リビング 涼しく
  icon: mdi:weather-windy
switch.cool_bedroom:
  friendly_name: 寝室 涼しく
  icon: mdi:weather-windy
group.useful_autumn:
  friendly_name: 便利 (秋)
group.useful_spring:
  friendly_name: 便利 (春)
group.useful_summer:
  friendly_name: 便利 (夏)
group.useful_winter:
  friendly_name: 便利 (冬)
proximity.home2:
  hidden: true
sensor.hue_dimmer_switch:
  hidden: true
sensor.hue_tap_switch:
  hidden: true
light.bedroom:
  friendly_name: ランプ
light.entrance:
  hidden: true
binary_sensor.hue_motion_motion_sensor:
  friendly_name: 玄関動き
light.hue_go:
  hidden: true
sensor.bedroom_temp_stat_mean:
  device_class: temperature
  friendly_name: 寝室 平均気温
  unit_of_measurement: °C
sensor.outdoor_stat_mean:
  device_class: temperature
  friendly_name: 屋外 平均気温
  unit_of_measurement: °C
sensor.living_temp_stat_mean:
  device_class: temperature
  friendly_name: リビング 平均気温
  unit_of_measurement: °C
sensor.entrance_temp:
  device_class: temperature
  friendly_name: 玄関 気温
  icon: mdi:thermometer
  unit_of_measurement: °C
sensor.entrance_lux:
  device_class: illuminance
  friendly_name: 玄関 明るさ
  icon: mdi:lightbulb-outline
  unit_of_measurement: lux
lock.door_lock:
  friendly_name: 鍵
device_tracker.iphone_se_2:
  friendly_name: iPhone SE bt
  hidden: true
sensor.jr_info:
  hidden: true
fan.living_circulator:
  friendly_name: サーキュレーター
sensor.dishwasher_power:
  friendly_name: 食洗機電力
  icon: mdi:lightbulb-on
  unit_of_measurement: W
group.entrance:
  friendly_name: 玄関
group.family_devices:
  hidden: true
group.my_devices:
  hidden: true
group.partner_devices:
  hidden: true
climate.2:
  hidden: true
sensor.inside_temperature_inside_temperature:
  hidden: true
sensor.inside_temperature_inside_temperature_2:
  hidden: true
sensor.outside_temperature_outside_temperature:
  hidden: true
sensor.outside_temperature_outside_temperature_2:
  hidden: true
sensor.ipad_battery_level:
  hidden: true
sensor.ipad_battery_state:
  hidden: true
sensor.netatmo_outdoor_battery_percent:
  hidden: true
input_boolean.sleeping:
  friendly_name: 就寝中
binary_sensor.hue_motion_sensor_motion:
  friendly_name: 玄関 動き
sensor.hue_motion_sensor_light_level:
  hidden: true
sensor.hue_motion_sensor_temperature:
  hidden: true
sensor.outdoor0:
  device_class: temperature
  hidden: true
sensor.outdoor1:
  device_class: temperature
  hidden: true
sensor.netatmo_outdoor_max_temp:
  hidden: true
sensor.netatmo_outdoor_min_temp:
  hidden: true
sensor.netatmo_house_max_temp:
  hidden: true
sensor.netatmo_house_min_temp:
  hidden: true
