#default_view:
#  view: yes
#  icon: mdi:home
#  entities:
#    - group.useful
#    - group.living
#    - group.bedroom
#    - group.house
#    - camera.doorphone
#    - group.music

useful_spring:
  name: Useful Spring
  control: hidden
  entities:
    - switch.heat_living
    - switch.heat_bedroom
    - switch.cool_living
    - switch.cool_bedroom

useful_summer:
  name: Useful Summer
  control: hidden
  entities:
    - switch.cool_living
    - switch.cool_bedroom

useful_autumn:
  name: Useful Autumn
  control: hidden
  entities:
    - switch.heat_living
    - switch.heat_bedroom
    - switch.cool_living
    - switch.cool_bedroom

useful_winter:
  name: Useful Winter
  control: hidden
  entities:
    - switch.heat_living
    - switch.heat_bedroom

living:
  name: Living Room
  control: hidden
  entities:
    - sensor.living_temperature
    - sensor.living_humidity
    - sensor.netatmo_house_temperature
    - sensor.netatmo_house_humidity
    - sensor.netatmo_house_co2
    - climate.living_aircon
    - fan.living_circulator
    - switch.ceiling_fan
    - switch.floor_heater_living
    - switch.floor_heater_kitchen

bedroom:
  name: Bed Room
  control: hidden
  entities:
    - sensor.bedroom_temperature
    - sensor.bedroom_humidity
    - climate.bedroom_aircon
    - light.hue_go

house:
  name: House
  control: hidden
  entities:
    - lock.door_lock
    - sensor.hue_motion_motion_sensor
    - sensor.house_power
    - sensor.entrance_lux
    - sensor.entrance_temp
    - sensor.outdoor
    - sensor.netatmo_outdoor_temperature
    - sensor.netatmo_outdoor_humidity
    - sensor.netatmo_house_pressure
    - sensor.netatmo_house_noise
    - binary_sensor.dishwasher

setting:
  name: Setting
  control: hidden
  entities:
    - input_number.heat_temp
    - input_number.cool_temp
    - sensor.outdoor_stat_mean
    #- sensor.living_temp_stat_mean
    #- sensor.bedroom_temp_stat_mean

music:
  name: Music
  control: hidden
  entities:
    - media_player.squeezebox_bedroom
    - media_player.squeezebox_living

family_devices:
  control: hidden
  entities:
    - device_tracker.iphonex
    - device_tracker.iphonex_2
    - device_tracker.iphone_se
    - device_tracker.iphone_se_2

my_devices:
  control: hidden
  entities:
    - device_tracker.iphonex
    - device_tracker.iphonex_2

partner_devices:
  control: hidden
  entities:
    - device_tracker.iphone_se
    - device_tracker.iphone_se_2

