#default_view:
#  view: yes
#  icon: mdi:home
#  entities:
#    - group.useful
#    - group.living
#    - group.bedroom
#    - group.house
#    - camera.doorphone
#    - group.music

useful_spring:
  name: Useful Spring
  control: hidden
  entities:
    - switch.heat_living
    - switch.heat_bedroom
    - switch.cool_living
    - switch.cool_bedroom

useful_summer:
  name: Useful Summer
  control: hidden
  entities:
    - switch.cool_living
    - switch.cool_bedroom

useful_autumn:
  name: Useful Autumn
  control: hidden
  entities:
    - switch.heat_living
    - switch.heat_bedroom
    - switch.cool_living
    - switch.cool_bedroom

useful_winter:
  name: Useful Winter
  control: hidden
  entities:
    - switch.heat_living
    - switch.heat_bedroom

entrance:
  name: Entrance
  control: hidden
  entities:
    - lock.door_lock
    - binary_sensor.hue_motion_sensor_motion
    - sensor.entrance_lux
    - sensor.entrance_temp

living:
  name: Living Room
  control: hidden
  entities:
    - sensor.living_temperature
    - sensor.living_humidity
    - sensor.netatmo_house_temperature
    - sensor.netatmo_house_humidity
    - sensor.netatmo_house_co2
    - climate.living_aircon
    - fan.living_circulator
    - switch.ceiling_fan
    - switch.floor_heater_living
    - switch.floor_heater_kitchen

bedroom:
  name: Bed Room
  control: hidden
  entities:
    - sensor.bedroom_temperature
    - sensor.bedroom_humidity
    - climate.bedroom_aircon
    - light.bedroom
    - input_boolean.sleeping

house:
  name: House
  control: hidden
  entities:
    - sensor.house_power
    - sensor.dishwasher_power
    - sensor.outdoor_temperature
    - sensor.netatmo_outdoor_temperature
    - sensor.netatmo_outdoor_humidity
    - sensor.netatmo_house_pressure
    - sensor.netatmo_house_noise
    - binary_sensor.dishwasher

setting:
  name: Setting
  control: hidden
  entities:
    - sensor.outdoor_average
    - sensor.outdoor_stat_mean
    - binary_sensor.cond_hot
    - binary_sensor.cond_cold
    - binary_sensor.cond_very_cold

music:
  name: Music
  control: hidden
  entities:
    - media_player.squeezebox_bedroom
    - media_player.squeezebox_living

family_devices:
  control: hidden
  entities:
    - person.me
    - person.partner

