#default_view:
#  view: yes
#  icon: mdi:home
#  entities:
#    - group.useful
#    - group.living
#    - group.bedroom
#    - group.house
#    - camera.doorphone
#    - group.music

useful:
  name: Useful tasks
  control: hidden
  entities:
    - switch.heat_living
    - switch.heat_bedroom
#    - switch.cool_living
#    - switch.cool_bedroom

living:
  name: Living Room
  control: hidden
  entities:
    - sensor.living_temperature
    - sensor.living_humidity
    - sensor.netatmo_house_temperature
    - sensor.netatmo_house_humidity
    - sensor.netatmo_house_co2
    - climate.living_aircon
    - switch.ceiling_fan
    - switch.floor_heater_living
    - switch.floor_heater_kitchen

bedroom:
  name: Bed Room
  control: hidden
  entities:
    - sensor.bedroom_temperature
    - sensor.bedroom_humidity
    - climate.bedroom_aircon

house:
  name: House
  control: hidden
  entities:
    - lock.door_lock
    - sensor.house_power
    - sensor.outdoor
    - sensor.netatmo_outdoor_temperature
    - sensor.netatmo_outdoor_humidity
    - sensor.netatmo_house_pressure
    - sensor.netatmo_house_noise
    - binary_sensor.dishwasher
    - binary_sensor.workday_sensor
    - sensor.weather_forecast
    #- sensor.owm_condition
    #- sensor.owm_forecast
    #- sensor.owm_rain

music:
  name: Music
  control: hidden
  entities:
    - media_player.squeezebox_bedroom
    - media_player.squeezebox_living

