
heat_living:
  alias: Heat Living
  sequence:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.living_aircon
        operation_mode: heat
    - service: switch.turn_on
      entity_id: switch.floor_heater_living
    - service: switch.turn_on
      entity_id: switch.floor_heater_kitchen

heat_bedroom:
  alias: Heat Bedroom
  sequence:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom_aircon
        operation_mode: heat

cool_living:
  alias: Cool Living
  sequence:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.living_aircon
        operation_mode: cool

cool_bedroom:
  alias: Cool Bedroom
  sequence:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom_aircon
        operation_mode: cool

off_living:
  alias: Off Living
  sequence:
    - service: switch.turn_off
      entity_id: switch.floor_heater_living
    - service: switch.turn_off
      entity_id: switch.floor_heater_kitchen
    - condition: template
      value_template: "{{ not is_state('climate.living_aircon', 'off') }}"
    - service: climate.set_operation_mode
      data:
        entity_id: climate.living_aircon
        operation_mode: off

off_bedroom:
  alias: Off Bedroom
  sequence:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom_aircon
        operation_mode: off

goodnight:
  alias: Good Night
  sequence:
    - service: script.turn_on
      entity_id: script.off_living
    - service: script.turn_on
      entity_id: script.check_dishwasher
    - delay:
        minutes: 3
    - service: script.turn_on
      entity_id: script.off_bedroom

check_dishwasher:
  alias: Check Dishwasher
  sequence:
    - condition: state
      entity_id: binary_sensor.dishwasher
      state: 'off'
    - service: tts.google_say
      entity_id: media_player.google_living
      data_template:
        message: >
          食洗機がついてません。

notify_energy:
  alias: Notify Energy
  sequence:
    - service: media_player.google_living
      data_template:
        entity_id: media_player.google_living
        volume_level: 0.7
    - service: tts.google_say
      entity_id: media_player.google_living
      data_template:
        message: >
          電力は {{states('sensor.house_power')}} watt です。

notify_kujitenda0:
  alias: Notify Kujitenda Start
  sequence:
    - service: script.notify_speech
      data:
        message: "ジャンボくじテンダーの時間ですよ。"

notify_kujitenda1:
  alias: Notify Kujitenda End
  sequence:
    - service: script.notify_speech
      data:
        message: "ジャンボくじテンダーの交換しましたか？"

#notify_weather:
#  alias: Notify Weather
#  sequence:
#    - service: media_player.google_living
#      data_template:
#        entity_id: media_player.google_living
#        volume_level: 0.7
#    - service: tts.google_say
#      entity_id: media_player.google_living
#      data_template:
#        message: >
#          {{states('sensor.weather_forecast')}}

notify_weather:
  alias: Notify Weather
  sequence:
    - service: media_player.google_living
      data_template:
        entity_id: media_player.google_living
        volume_level: 0.7
    - service: media_player.play_media
      data:
        entity_id: media_player.google_living
        media_content_id: 'http://minabe.org/forecast.wav'
        media_content_type: 'audio/wav'

notify_speech:
  alias: Notify Speech
  sequence:
    - service: media_player.google_living
      data_template:
        entity_id: media_player.google_living
        volume_level: 0.6
    - service: tts.google_say
      entity_id: media_player.google_living
      data_template:
        message: "{{ message }}"


