# sensors

- platform: season

- platform: mqtt
  state_topic: "sensor/watt"
  name: 'House Power'
  unit_of_measurement: 'W'
- platform: mqtt
  state_topic: "sensor/aircon/livingroom/outtemp"
  name: 'Outdoor0'
- platform: mqtt
  state_topic: "sensor/aircon/bedroom/outtemp"
  name: 'Outdoor1'
- platform: mqtt
  state_topic: "sensor/aircon/livingroom/temperature"
  name: 'Living Temperature'
- platform: mqtt
  state_topic: "sensor/aircon/livingroom/humidity"
  name: 'Living Humidity'
  unit_of_measurement: '%'
- platform: mqtt
  state_topic: "sensor/aircon/bedroom/temperature"
  name: 'Bedroom Temperature'
- platform: mqtt
  state_topic: "sensor/aircon/bedroom/humidity"
  name: 'Bedroom Humidity'
  unit_of_measurement: '%'

- platform: statistics
  name: outdoor_stat
  entity_id: sensor.outdoor_temperature
  sampling_size: 1500
  max_age:
    hours: 24
#- platform: statistics
#  name: living_temp_stat
#  entity_id: sensor.living_temperature
#  sampling_size: 1500
#  max_age:
#    hours: 24
#- platform: statistics
#  name: bedroom_temp_stat
#  entity_id: sensor.bedroom_temperature
#  sampling_size: 1500
#  max_age:
#    hours: 24

- platform: template
  sensors:
    outdoor_temperature:
      value_template: "{{ ((states.sensor.outdoor0.state|float)+(states.sensor.outdoor1.state|float))/2.0 }}"

    entrance_temp:
      value_template: "{{ states.sensor.hue_motion_sensor_temperature.state }}"

    entrance_lux:
      value_template: "{{ states.sensor.hue_motion_sensor_light_level.state|round(1) }}"

    dishwasher_power:
      value_template: >-
        {% if is_state("switch.washer", "on") -%}
          {{ states.switch.washer.attributes.current_power_w }}
        {%- else -%}
          0
        {%- endif %}

- platform: folder
  folder: /config/doorphone

- platform: template
  sensors:
    doorphone_counter:
      value_template: "{{ states.sensor.doorphone.attributes.number_of_files }}"

- platform: file
  name: trash_day
  file_path: /config/text/gomi.txt

- platform: file
  name: visit_schedule
  file_path: /config/text/schedule.txt

- platform: file
  name: weather_forecast
  file_path: /config/text/forecast.txt

#- platform: scrape
#  resource: http://weather.livedoor.com/forecast/rss/area/130010.xml
#  name: weather_forecast
#  select: 'description:nth-of-type(3)'
#  value_template: '{{ value }}'

- platform: netatmo
  modules:
    House:
      - temperature
      - humidity
      - pressure
      - co2
      - noise
    Outdoor:
      - temperature
      - humidity

- platform: scrape
  name: JR info
  scan_interval: 900
  resource: http://traininfo.jreast.co.jp/train_info/kanto.aspx
  select: "#direction_yamate tbody"
  value_template: '{{ (value.strip().replace("配信","").replace("更新履歴","")) }}'

