# switch

- platform: mqtt
  name: "Floor Heater Living"
  command_topic: "dio/set0"
  state_topic:   "dio/in0"
  payload_on:  "1"
  payload_off: "0"
  retain: true
- platform: mqtt
  name: "Floor Heater Kitchen"
  command_topic: "dio/set1"
  state_topic:   "dio/in1"
  payload_on:  "1"
  payload_off: "0"
  retain: true

- platform: template
  switches:
    heat_living:
      value_template: >-
        {{     is_state('climate.living_aircon', 'heat')
           and is_state('switch.floor_heater_living', 'on')
           and is_state('switch.floor_heater_kitchen', 'on') }}
      turn_on:
        service: script.turn_on
        entity_id: script.heat_living
      turn_off:
        service: script.turn_on
        entity_id: script.off_living
    heat_bedroom:
      value_template: >-
        {{ is_state('climate.bedroom_aircon', 'heat') }}
      turn_on:
        service: script.turn_on
        entity_id: script.heat_bedroom
      turn_off:
        service: script.turn_on
        entity_id: script.off_bedroom
    cool_living:
      value_template: >-
        {{ is_state('climate.living_aircon', 'cool') }}
      turn_on:
        service: script.turn_on
        entity_id: script.cool_living
      turn_off:
        service: script.turn_on
        entity_id: script.off_living
    cool_bedroom:
      value_template: >-
        {{ is_state('climate.bedroom_aircon', 'cool') }}
      turn_on:
        service: script.turn_on
        entity_id: script.cool_bedroom
      turn_off:
        service: script.turn_on
        entity_id: script.off_bedroom

- platform: broadlink
  host: 192.168.0.61
  mac: !secret broadlink_mac

  timeout: 20
  switches:
    ceiling_fan:
      command_on: 'JgCEAxANEAwRKRAMESkQKRAMEQwQKREMEA0QDBEMECkQDRAMEQwQDRApECkQDRAMESkQDBEMEA0QDBApEQwQDRApEA0QDBANEAwRDBANEAwRDBAMESkQDBEMEA0QKRANEAAKGXM3EQwQKREMEA0QDBEMEA0QDBANEAwRDBANEAwRKRAMEA0QDBEMEA0QDBEpEAwQKREpEAwRDBApEA0QDBEMEA0QKRANEAwQDRAMESkQKRANEAwQKREMEA0QDBEMECkQDRAMESkQDBEMEA0QDBANEAwRDBANEAwRKRAMEA0QDBEpEAwRAAoYdDcRDBApEA0QDBEMEA0QDBEMEA0QDBANEAwRDBApEQwQDRAMEA0QDBEMECkRDBApECkRDBANECkQDRAMEA0QDBEpEAwRDBANEAwQKREpEAwRDBApEA0QDBEMEA0QKRANEAwQKREMEA0QDBEMEA0QDBANEA0QDBApEQwQDRAMECoQDBAAChl0NxANECkQDRAMEQwQDBEMEA0QDBEMEA0QDBANECkQDRAMEQwQDRAMEA0QKRANECkQKRANEAwRKRAMEQwQDRAMECoQDBANEAwRDBApESkQDBANECkQDRAMEQwQDRApEAwRDBApEQwQDRAMEA0QDBEMEA0QDBEMECkQDRAMEQwQKREMEAAKGXQ3EA0QKRAMEQwQDRAMEQwQDRAMEQwQDBEMEA0QKRANEAwQDRAMEQwQDRApEA0QKRApEA0QDBEpEAwRDBANEAwQKREMEA0QDBEMECkQKREMEA0QKRAMEQwQDRAMESkQDBEMECkQDRAMEQwQDRAMEQwQDRAMEA0QKRANEAwRDBApEA0QAAoZczgQDBAqEAwQDRAMEQwQDRAMEA0QDRAMEA0QDBEpEAwQDRANEAwQDRAMESkQDBAqECkQDBEMECkQDRANEAwQDRApEA0QDBANEA0QKRApEA0QDBAqEAwQDRAMEQwQKRANEA0QKRAMEQwQDRAMEQwQDRAMEA0QDBEpEAwQDRANECkQDBEAChlzOBAMECkRDBANEAwRDBANEAwQDRAMEQwQDRAMESkQDBANEAwRDBANEAwRKRAMECkRKRAMEQwQKRANEAwRDBANECkQDRAMEA0QDBEpECkQDRAMECkRDBANEAwRDBApEA0QDRApEAwRDBANEAwRDBANEAwQDRAMESkQDBEMEAwRKRAMEQANBQAAAAA='
      command_off: 'JgCEAxAMEQwQKRANECkQKREMEA0QKRAMEQwQDRAMESkQDBANEAwRDBApESkQDBANECkQKREMEA0QKRApEA0QDBEMEA0QDBANECkQKREMEAwRKRApECkRDBAMESkQKRANEAAKGXQ3EQwQKREMEA0QDBEMEAwRDBANEAwRDBANEAwQKREMEA0QDBEMEA0QDBApEQwQKREpEAwQDRApEA0QDBEMEA0QKRAMEQwQDRAMESkQKRAMEQwQKREpEAwQDRApECkRDBANEAwQDRAMEQwQKREpEAwQDRApECkRKBEMEA0QKRApEQwQAAoaczgQDBEpEAwQDRAMEQwQDRAMEQwQDRAMEA0QDBEpEAwRDBANEAwQDRAMESkQDBEpECkQDBEMECkRDBANEAwQDRApEA0QDBEMEA0QKRApEA0QDBEpECkQDBEMECkRKBEMEA0QDBEMEA0QDBApESkQDBEMECkQKREpEAwRDBApECkRDBAAChpzOBANECkQDBEMEA0QDBEMEA0QDQ8NEAwRDBANECkQDRAMEA0QDBEMEA0QKRANECkQKRANEAwRKRAMEA0QDBEMECkRDBANEAwQDRApECkRDBANECkQKRANEAwRKRApEAwRDBANEAwRDBANECkQKRANEAwQKhApECkQDRAMECkRKRAMEQAKGXQ3EA0QKRANEAwRDBANEAwQDRAMEQwQDRAMEQwQKRANEAwRDBANEAwRDBApEA0QKRApEQwQDRApEAwRDBANEAwRKRAMEA0QDBEMECkRKRAMEA0QKRApEQwQDBEpECkQDRAMEQwQDRAMEA0QKRApEQwQDRApECkQKREMEA0QKRApEA0QAAoZdDcRDBApEQwQDRAMEA0QDBEMEA0QDBEMEA0QDBApEQwQDRAMEQwQDRAMECkRDBApESgRDBANECkQDRAMEQwQDRApEAwRDBANEAwRKBEpEAwRDBApESgRDBANECkQKREMEA0QDBANEAwRDBApESgRDBANECkQKREoEQwQDRApECkRDBAAChpzOBAMESgRDBANEAwRDBANEAwRDBANEAwQDRAMESkQDBANEAwRDBANEAwRKRAMECkRKRAMEA0QKRANEAwRDBANECkQDRAMEA0PDRAqECkQDQ8NDyoQKg8NDw4PKg8qDw4ODw4ODg8ODw4ODisPKw8NDg8OKw4rDiwPDQ4PDisOKRAPDgANBQAAAAA='

    blind:
      # close blind
      command_on: 'JgByAwABF4kTDxMQEzITMhQyEw8UDxMQE4gUMhMQEw8TEBMPFA8TEBMPFAADGQABF4gTEBMPFDITMhMyFA8TEBMPE4kTMhQPExATDxQPExATDxQPEwADGgABFIsSEBMQEzIUMhMyFA4UDxQPFIgTMhQPEw8UDxQOExAUDxMPEwADGgABF4gTEBMQEjMRNBE0ERIREhEREYsRNBESERIRERESERIRERESEQADHAABFokTDxQPEzIUMhMyExATDxMQE4kTMhMQEw8UDxMQEw8UDxMQEwADGQABF4gUDxMQEzITMhMzEw8TEBMPFIgUMhMPExATEBMPExATDxQPEwADGgABFokTEBMPEzIUMhMyExATDxQPE4kTMhMQEw8UDxMQEw8UDxMQEwADGQABF4gUDxMQEzITMhMzEw8TEBMPFIgUMhMPFA8TEBMPExATEBMPEwADGgABFokUDxMPEzIUMhMyExATDxQPE4kUMRQPEw8UDxMQEw8UDxMQEwADGQABGIcUDxMQEzIUMRQyFA4TEBMQE4gUMhQOFA8TEBMPExATEBMPEwADGgABF4gUDxMPEzMUMRQxFA8TDxQPE4kUMRQPExATDxMQEw8UDxMQEwADGQABGIcUDxMQEzITMhQyFA4TEBMQE4gUMhQOFA8TEBMPFA8TEBMPEwADGgABF4gUDxMPEzMUMRQxFA8TEBMPE4kUMRQPFA8UDhMQExATDxMQEwADGQABGIgUDhMQEzIUMRQyFA4UDxMQE4kUMRQPEw8TEBMPFA8TEBMPFAADGQABF4gUDxMPFDIUMRQxFA8TEBMPE4kUMRQPExATDxMQExATDxMQEwADGQABGIgUDhQPEzIUMhMyFA4UDxMQE4kUMRQPEw8UDxMQEw8TEBMPFAADGQABGIcUDxQOFDIUMRQxFA8TEBMPE4kUMRQPExATDxQPExATDxMQEwADGgABF4gUDhQPEzIUMhQxFA8TDxMQE4kUMRQPEw8TEBMQEw8TEBMQEwADGQABGIcUDxMQEzIUMRQxFA8TEBMPE4kUMhMPFA8TDxQPExATDxQPEwADGgABF4gUDhQPEzIUMhQxFA8TDxMQE4kUMRQPEw8TEBMQEw8TEBMQEwADGQABF4gTEBMQEzITMhMyExATEBMPE4kTMxMPExATDxMQExATDxMQEwANBQAAAAAAAA=='
      # close open
      command_off: 'JgAeAwABF4gTEBMQEzITMhMzEw8TEBMQE4YVEBMyExATMhMQExATDxMQEwAC9wABFokTEBMPEzMTMhMyExATEBIQE4kTEBMyExATMhMQEw8TEBMQEgAC9wABF4kTDxMQEzITMxMyExASEBMQE4kTDxMzEw8TMxMPExATEBIQEwAC9wABF4gTEBMQEzITMhMzEhATEBMPE4kTEBMyExATMhMQExASEBMQEwAC9wABFokTEBMPEzMSMxMyExATDxMQE4kTEBMyExASMxMQEhATEBMPEwAC9wABF4gUDxMQEzITMxIzEw8TEBMQE4kTDxMzEhATMhMQExATDxMQEwAC9wABF4gTEBMQEjMTMhMyExATEBMPE4kTEBMyExATMhMQEw8TEBMQEwAC9wABFokTEBIQEzITMxMyExATDxMQE4kTEBIzEw8TMxMPExATEBMPEwAC9wABF4gTEBMQEzITMhMzEw8TEBMQEokTEBMyExATMhMQExATDxMQEwAC9wABFokTEBMPEzMTMhMyExATEBIQE4kTEBMyExATMhMQEw8TEBMQEgAC9wABF4kTDxMQEzITMxIzExASEBMQE4kTDxMzEw8TMxIQExATEBIQEwAC9wABF4gTEBMQEjMTMhMyExATEBMPE4kTEBMyExATMhMQExASEBMQEwAC9wABFokTEBIQEzITMxMyExATDxMQE4kTEBIzExASMxMPExATEBMPEwAC9wABF4gUDxMQEzITMhMzEw8TEBMQE4gTEBMyExATMhMQExATDxMQEwAC9wABFokTEBMPEzMTMhMyExATEBIQE4kTEBMyExATMhMQEw8TEBMQEgAC+AABFokTDxMQEzITMxIzExASEBMQE4kTDxMzEw8TMxMPExATEBIQEwAC9wABF4gTEBMQEzITMhMzEhATEBMQEokTEBMyExATMhMQExASEBMQEwAC9wABFokTEBMPEzMSMxMyExATDxMQE4kTEBMyExASMxMQEhATEBMPEwAC9QABGYkTDxMQEzITMhMzEw8TEBMQE4kTDxMyExATMhMQExATDxMQEwANBQAAAAAAAAAAAAA='

