heat_living:
  alias: Heat Living
  sequence:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.living_aircon
        operation_mode: Heat
    - service: climate.set_temperature
      data:
        entity_id: climate.living_aircon
        temperature: 24
    - service: switch.turn_on
      entity_id: switch.floor_heater_living
    - service: switch.turn_on
      entity_id: switch.floor_heater_kitchen

heat_bedroom:
  alias: Heat Bedroom
  sequence:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom_aircon
        operation_mode: Heat
    - service: climate.set_temperature
      data:
        entity_id: climate.bedroom_aircon
        temperature: 24

heat_living_demand:
  alias: Heat Living on Demand
  sequence:
    - service: script.turn_on
      entity_id: script.heat_living_floor_demand
    - condition: state
      entity_id: binary_sensor.cond_very_cold
      state: 'on'
    - service: script.turn_on
      entity_id: script.heat_living

heat_living_floor_demand:
  alias: Heat Living Floor on Demand
  sequence:
    - condition: state
      entity_id: binary_sensor.cond_cold
      state: 'on'
    - service: switch.turn_on
      entity_id: switch.floor_heater_living
    - service: switch.turn_on
      entity_id: switch.floor_heater_kitchen

heat_bedroom_demand:
  alias: Heat Bedroom on Demand
  sequence:
    - condition: state
      entity_id: binary_sensor.cond_very_cold
      state: 'on'
    - service: script.turn_on
      entity_id: script.heat_bedroom

cool_living:
  alias: Cool Living
  sequence:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.living_aircon
        operation_mode: Cool
    - service: climate.set_temperature
      data:
        entity_id: climate.living_aircon
        temperature: 28
    - service: switch.turn_off
      entity_id: switch.floor_heater_living
    - service: switch.turn_off
      entity_id: switch.floor_heater_kitchen

cool_bedroom:
  alias: Cool Bedroom
  sequence:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom_aircon
        operation_mode: Cool
    - service: climate.set_temperature
      data:
        entity_id: climate.bedroom_aircon
        temperature: 30

cool_living_demand:
  alias: Cool Living on Demand
  sequence:
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.living_temperature
          above: 29
        - condition: state
          entity_id: binary_sensor.cond_hot
          state: 'on'
    - service: script.turn_on
      entity_id: script.cool_living

cool_bedroom_demand:
  alias: Cool Bedroom on Demand
  sequence:
    - condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.bedroom_temperature
          above: 29
        - condition: time
          after: '00:00:00'
          before: '02:00:00'
    - service: script.turn_on
      entity_id: script.cool_bedroom

comfort_living:
  alias: Comfort Living on Demand
  sequence:
    - service: script.turn_on
      entity_id: script.heat_living_demand
    - service: script.turn_on
      entity_id: script.cool_living_demand

comfort_living_slow:
  alias: Comfort Living Slow on Demand
  sequence:
    - service: script.turn_on
      entity_id: script.heat_living_floor_demand
    - delay:
        minutes: 10
    - service: script.turn_on
      entity_id: script.heat_living_demand
    - service: script.turn_on
      entity_id: script.cool_living_demand

comfort_bedroom:
  alias: Comfort Bedroom on Demand
  sequence:
    - service: script.turn_on
      entity_id: script.heat_bedroom_demand
    - service: script.turn_on
      entity_id: script.cool_bedroom_demand

off_living:
  alias: Off Living
  sequence:
    - service: switch.turn_off
      entity_id: switch.floor_heater_living
    - service: switch.turn_off
      entity_id: switch.floor_heater_kitchen
    - service: homeassistant.turn_off
      entity_id: switch.ceiling_fan
    - condition: template
      value_template: "{{ not is_state('climate.living_aircon', 'off') }}"
    - service: climate.set_operation_mode
      data:
        entity_id: climate.living_aircon
        operation_mode: off

off_bedroom:
  alias: Off Bedroom
  sequence:
    - condition: template
      value_template: "{{ not is_state('climate.bedroom_aircon', 'off') }}"
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom_aircon
        operation_mode: off

off_heat_bedroom:
  alias: Off Heat Bedroom
  sequence:
    - condition: template
      value_template: "{{ is_state('climate.bedroom_aircon', 'heat') }}"
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom_aircon
        operation_mode: off

im_home:
  alias: I'm Home
  sequence:
    - service: script.turn_on
      entity_id: script.comfort_living

