heat_living:
  alias: Heat Living
  sequence:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.living_aircon
        operation_mode: heat
    - service: switch.turn_on
      entity_id: switch.floor_heater_living
    - service: switch.turn_on
      entity_id: switch.floor_heater_kitchen

heat_living_demand:
  alias: Heat Living on Demand
  sequence:
    - condition: template
      value_template: "{{ states('sensor.outdoor_stat_mean')|float < (states('input_number.heat_temp')|float) }}"
    - service: switch.turn_on
      entity_id: switch.floor_heater_living
    - service: switch.turn_on
      entity_id: switch.floor_heater_kitchen
    - condition: template
      value_template: "{{ states('sensor.outdoor_stat_mean')|float < (states('input_number.heat_temp')|float)-3.0 }}"
    - service: climate.set_operation_mode
      data:
        entity_id: climate.living_aircon
        operation_mode: heat

heat_bedroom:
  alias: Heat Bedroom
  sequence:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom_aircon
        operation_mode: heat

heat_bedroom_demand:
  alias: Heat Bedroom on Demand
  sequence:
    - condition: template
      value_template: "{{ states('sensor.outdoor_stat_mean')|float < (states('input_number.heat_temp')|float)-3.0 }}"
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom_aircon
        operation_mode: heat

cool_living:
  alias: Cool Living
  sequence:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.living_aircon
        operation_mode: cool
    - service: switch.turn_off
      entity_id: switch.floor_heater_living
    - service: switch.turn_off
      entity_id: switch.floor_heater_kitchen

cool_living_demand:
  alias: Cool Living on Demand
  sequence:
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.living_temperature
          above: 29
        - condition: template
          value_template: "{{ states('sensor.outdoor_stat_mean')|float > (states('input_number.cool_temp')|float) }}"
    - service: climate.set_operation_mode
      data:
        entity_id: climate.living_aircon
        operation_mode: cool
    - service: switch.turn_off
      entity_id: switch.floor_heater_living
    - service: switch.turn_off
      entity_id: switch.floor_heater_kitchen

cool_bedroom:
  alias: Cool Bedroom
  sequence:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom_aircon
        operation_mode: cool

cool_bedroom_demand:
  alias: Cool Bedroom on Demand
  sequence:
    - condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.bedroom_temperature
          above: 29
        - condition: time
          after: '00:00:00'
          before: '02:00:00'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom_aircon
        operation_mode: cool

off_living:
  alias: Off Living
  sequence:
    - service: switch.turn_off
      entity_id: switch.floor_heater_living
    - service: switch.turn_off
      entity_id: switch.floor_heater_kitchen
    - service: homeassistant.turn_off
      entity_id: switch.ceiling_fan
    - condition: template
      value_template: "{{ not is_state('climate.living_aircon', 'off') }}"
    - service: climate.set_operation_mode
      data:
        entity_id: climate.living_aircon
        operation_mode: off

off_bedroom:
  alias: Off Bedroom
  sequence:
    - condition: template
      value_template: "{{ not is_state('climate.bedroom_aircon', 'off') }}"
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom_aircon
        operation_mode: off

off_heat_bedroom:
  alias: Off Bedroom
  sequence:
    - condition: template
      value_template: "{{ is_state('climate.bedroom_aircon', 'heat') }}"
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom_aircon
        operation_mode: off

im_home:
  alias: I'm Home
  sequence:
    - service: script.turn_on
      entity_id: script.heat_living_demand
    - service: script.turn_on
      entity_id: script.cool_living_demand

